# Generated by Django 5.2.15 on 2026-06-25 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('required_skills', models.JSONField(default=list)),
                ('timeline_months', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=255)),
                ('missing_skills', models.JSONField(default=list)),
                ('existing_skills', models.JSONField(default=list)),
                ('skill_levels', models.JSONField(default=dict)),
                ('analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
