# Generated by Django 5.0.6 on 2026-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
