# Generated by Django 5.0.14 on 2026-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resumeanalysis_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='raw_extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
