# Generated by Django 5.0.14 on 2026-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_add_resume_fk_and_anchored_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
